//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ES_Problems_With_Car
{
    using System;
    using System.Collections.Generic;
    
    public partial class Car_System_Nodes
    {
        public Car_System_Nodes()
        {
            this.Defect_Reasons = new HashSet<Defect_Reasons>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
        public int SystemID { get; set; }
        public bool IsSelected { get; set; }
        public bool WasViewed { get; set; }
        public bool IsDeleted { get; set; }
    
        public virtual Car_Systems Car_Systems { get; set; }
        public virtual ICollection<Defect_Reasons> Defect_Reasons { get; set; }
    }
}
