//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ES_Problems_With_Car
{
    using System;
    using System.Collections.Generic;
    
    public partial class Car_Defects
    {
        public Car_Defects()
        {
            this.Reasons_Correction_Methods = new HashSet<Reasons_Correction_Methods>();
        }
    
        public int ID { get; set; }
        public int ReasonID { get; set; }
        public bool IsSelected { get; set; }
        public string Answer { get; set; }
        public bool WasViewed { get; set; }
        public bool IsDeleted { get; set; }
    
        public virtual Defect_Reasons Defect_Reasons { get; set; }
        public virtual ICollection<Reasons_Correction_Methods> Reasons_Correction_Methods { get; set; }
    }
}
