//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ES_Problems_With_Car
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Exper_System_dbEntities : DbContext
    {
        public Exper_System_dbEntities()
            : base("name=Exper_System_dbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Car_Defects> Car_Defects { get; set; }
        public DbSet<Car_System_Nodes> Car_System_Nodes { get; set; }
        public DbSet<Car_Systems> Car_Systems { get; set; }
        public DbSet<Defect_Reasons> Defect_Reasons { get; set; }
        public DbSet<Reasons_Correction_Methods> Reasons_Correction_Methods { get; set; }
        public DbSet<Reasons_Diagnosis> Reasons_Diagnosis { get; set; }
    }
}
