//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ES_Problems_With_Car
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reasons_Correction_Methods
    {
        public int ID { get; set; }
        public int DefectID { get; set; }
        public string Answer { get; set; }
        public bool IsDeleted { get; set; }
    
        public virtual Car_Defects Car_Defects { get; set; }
    }
}
